
# Site Settings
name: Bytesize Architecture Sessions
title: Bytesize Architecture Sessions
description: A site about Bytesize Architecture Sessions. Bytesize Architecture Sessions created by Andrea Magnorsky  
url: https://bytesizearchitecturesessions.com
baseurl: ""


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate


# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"
locale: "en"
show_date: true

include: ["_pages"]
analytics:
  provider: "custom"


# Site Author
author:
  name: "Andrea Magnorsky"
  bio: "Creator of  Bytesize Architecture Sessions"
  avatar: "/images/avatars/am.jpeg"
  links:
  - label: "LinkedIn"
    icon: "fab fa-fw fa-linkedin"
    url: "https://www.linkedin.com/in/magnorsky/"
  - label: "Mastodon"
    icon: "fab fa-fw fa-mastodon"
    url: "https://types.pl/@roundcrisis"
  - label: "Book an appointment"
    icon: "fa-solid fa-calendar-days"
    url: "https://modelbridgesoftware.com"


defaults:
  # English posts
  - scope:
      path: "_posts/en"
      type: posts
    values:
      layout: single
      classes: wide
      permalink: "news/:title/"
      language: en
      author_profile: true
      read_time: false
      share: false
  # Spanish posts  
  - scope:
      path: "_posts/es"
      type: posts
    values:
      layout: single
      permalink: "noticias/:title/"
      language: es
      author_profile: true
      read_time: false
      share: false
  # Pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


sass:
  quiet_deps: true
  style: compressed